### ISSUE TITLE
[Question] Prometheus exporter service response time ?

### ISSUE THREAD

**Issue by suadev** [krakend/krakend-opencensus#48]
Hi,

We currently use KrakenD in production and we like it. We are trying to export metrics to Prometheus and visualize them on grafana. 

It seems Prometheus exporter doesn't export response time or we couldn't find it.  

Thanks in advance.

**Comment by CodyManshack-SAP** [comment]
Hi @suadev,

I also ran into this issue recently.

Basically, this is currently not possible. KrakenD currently interfaces with the [OCHTTP package](https://pkg.go.dev/go.opencensus.io/plugin/ochttp) package, indirectly through the exporters [OpenCensus Prometheus exporter](https://pkg.go.dev/contrib.go.opencensus.io/exporter/prometheus). The ochttp package does not collect detailed metrics, but only very basic metrics like latency, number of requests, and request size.

I am looking around to see if I can find a way to ingest the `/stats` endpoint somehow in Prometheus, but I don't think this is possible.

Until KrakenD decides to update to OpenTelemetry, Prometheus users are kinda screwed. Currently, the KrakenD team forces you to deploy and use InfluxDB if you want any useful metrics.
