### ISSUE TITLE
panic recovered: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0xqab** [krakend/krakend-opencensus#58]
Hello,

we are encountering a panic when using the krakend-opencensus middleware in krakend-ce v1.4.1. The panic is reproducable for some requests in one of our environments while not in all of them. We are using multiple custom krakend "server" plugins, but the plugins do not execute much relevant code for the failing requests as those requests are whitelisted and passed through.

I am not completely sure that this is an issue with the opencensus middleware, however I kindly ask you to have a look at the stacktrace and tell me your thoughts:
```
[GIN] 2021/11/30 - 15:32:57 | 500 | 576.582µs | 10.19.163.120 | GET "/some/path"

[maroon:]2021/11/30 15:32:57 [Recovery] 2021/11/30 - 15:32:57 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0xd4e35a)
/usr/local/go/src/runtime/signal_unix.go:734 (0xd67512)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http_transport.go:123 (0x196e137)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http_transport.go:89 (0x196e12f)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http_transport.go:179 (0x196e950)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http_transport.go:351 (0x196f856)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http_transport.go:119 (0x196e34f)
/usr/local/go/src/net/http/client.go:251 (0x105e813)
/usr/local/go/src/net/http/client.go:175 (0x105e1fe)
/usr/local/go/src/net/http/client.go:717 (0x106027e)
/usr/local/go/src/net/http/client.go:585 (0x1972a46)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/http.go:43 (0x1972917)
/go/pkg/mod/github.com/luraproject/lura@v1.4.1/proxy/http.go:68 (0x10ed22f)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/proxy.go:27 (0x1973a9a)
/go/pkg/mod/github.com/luraproject/lura@v1.4.1/proxy/balancing.go:76 (0x10ebfb6)
/go/pkg/mod/github.com/luraproject/lura@v1.4.1/proxy/http.go:109 (0x10ed950)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/proxy.go:27 (0x1973a9a)
/go/pkg/mod/github.com/luraproject/lura@v1.4.1/router/gin/endpoint.go:40 (0x191d611)
/go/pkg/mod/github.com/devopsfaith/krakend-opencensus@v1.4.1/router/gin/endpoint.go:70 (0x21acde1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x1917a79)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99 (0x1917a60)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x1916b53)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/logger.go:241 (0x1916b12)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x190cd09)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:489 (0x190ccef)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:445 (0x190c7db)
/plugin/plugin3/plugin3.go:130 (0x7fdacc836009)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/plugin/plugin2/plugin2.go:101 (0x7fdab91fba49)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/plugin/plugin1/plugin1.go:90 (0x7fdabb245ebe)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/plugin/plugin0/plugin0.go:40 (0x7fdabac4db6f)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 (0x1e2d910)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 (0x1e2d910)
/usr/local/go/src/net/http/server.go:2069 (0x10acc43)
/usr/local/go/src/net/http/server.go:2887 (0x10b0302)
/usr/local/go/src/net/http/server.go:1952 (0x10ab72c)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0xd88e40)
```

Plugin code in all four plugins very much looks like this for requests that fail:
```
return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
  span, spanCtx := apm.StartSpan(req.Context(), "handler", pluginName)
  if req.Method == http.MethodOptions || isWhitelistedPath(req.URL.EscapedPath()) {
    span.End()
    handler.ServeHTTP(w, req)
    return
  }
  // ... some other code not executed in failing requests ...
})
```
Plugins are using Elastic APM if that is relevant:
```
go.elastic.co/apm v1.11.0
go.elastic.co/apm/module/apmhttp v1.11.0
```

**Comment by iojas** [comment]
I am facing this issue as well with krakend:1.4.0. Did exactly as how Documentation says.

**Comment by iojas** [comment]
`"extra_config": {
        "github_com/devopsfaith/krakend-opencensus": {
            "sample_rate": 100,
            "reporting_period": 1,
            "enabled_layers": {
                "backend": true,
                "router": true,
                "pipe": true
            },
            "exporters": {
              "prometheus": {
                  "port": 9091,
                  "namespace": "krakend",
                  "tag_host": false,
                  "tag_path": true,
                  "tag_method": true,
                  "tag_statuscode": false
              }
          }
        }
     },`

This block of `extra_config` is working for me with version `devopsfaith/krakend:1.4.1`

I am not sure what has changes from version 1.4.0 to 1.4.1 to affect this functionality.

**Comment by alombarte** [comment]
Hello,

Thank you for opening this issue. KrakenD has traditionally offered its telemetry integration through this OpenCensus component, which has provided reliable service for over six years, but it is now transitioning to the more modern and robust [OpenTelemetry framework](https://www.krakend.io/docs/telemetry/opentelemetry/).

Due to a change in the industry, the OpenCensus integration is no longer maintained by its creators, and all efforts are focused on OpenTelemetry. KrakenD shifted to OTEL too.

Issues found with OTEL can be opened in the repository [krakend-otel](https://github.com/krakend/krakend-otel)

Thank you
