### ISSUE TITLE
Support for W3C Trace Context

### ISSUE THREAD

**Issue by bamorim** [krakend/krakend-opencensus#63]
Hey, first of all, thanks for krakend, I've been playing around with it today and found really awesome to use!

One thing I noticed, though, is that the only propagation standard supported is b3. Would you be also looking into implementing [W3C Trace Context](https://www.w3.org/TR/trace-context/)?

If so, I could try to give it a go, although I'm not the best go developer around 😅

Thanks

**Comment by mouradchama** [comment]
Hi, 

I'm also waiting for this feature, any news about it?

Regards,

**Comment by alombarte** [comment]
Hi @bamorim and @mouradchama ,

The OpenCensus component will soon be marked as deprecated and no further features will be added. We are transitioning to [krakend-otel](https://github.com/krakend/krakend-otel/) instead.

As we move forward with the OpenTelemetry implementation we will consider adding new features.
