### ISSUE TITLE
Stackdriver export context deadline exceeded

### ISSUE THREAD

**Issue by tfluehmann** [krakend/krakend-opencensus#70]
I have a krakend-ce (2.0.2) container running in gke (1.22.8-gke.202) and tried to enable tracing to stackdriver for this instance.
In order to do that I added the stackdriver configuration to my api configuration as described in here: https://www.krakend.io/docs/telemetry/stackdriver/
After that I received a few errors like get container clusters permission missing etc. I managed to fix that with by using workload identity described here: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
Now the logs tell me after the container started:
```
[SERVICE: OpenCensus] Service correctly registered
```
And then later
```
Failed to export to Stackdriver: rpc error = DeadlineExceeded desc = context deadline exceeded
```
My workload identity mapped service account has the roles:  metricWriter and clusterViewer
Any idea what I am missing? I don't have any network policies or something like that in place.

**Comment by alombarte** [comment]
Hi Tobias, 
Apologies for the late reply, you are probably not interested in the response by now or you have already sorted it out. The Context deadline exceed is a timeout trying to reach the service, and it means a network connectivity issue.

If you still use KrakenD, the OpenCensus component is being faded out and you might want to use OpenTelemetry instead.
