### ISSUE TITLE
Jaeger Exporter does not support UDP protocol

### ISSUE THREAD

**Issue by CodyManshack-SAP** [krakend/krakend-opencensus#71]
# Issue

**It is impossible to configure the opencensus plugin to post traces to a jaeger-agent.**

[KrakenD's OpenCensus package](https://github.com/krakendio/krakend-opencensus) only provides support for [Thrift over HTTP](https://www.jaegertracing.io/docs/1.23/apis/#thrift-over-http-stable). A common HA deployment pattern of Jaeger is to have 1..N **jaeger-agent** containers which accept traces and forward them to a central **jaeger-collector**. The **jaeger-agent** only supports [Thrift over UDP](https://www.jaegertracing.io/docs/1.23/apis/#thrift-over-udp-stable).

## Workarounds currently not possible
 * report directly to the central **jaeger-collector** over HTTP

All traffic at the collector is encrypted *by default*. There are no configuration options within the OpenCensus package to provide a certificate to sign these requests, and the certificate used for jaeger cannot be guaranteed to be the same certificate that signs all other requests in a KrakenD deployment.

## Other mentions of this issue
Issue #50 opened August of last year hints that this has been ran into before and may even be a common issue, but the user lacked the understanding to properly describe the issue encountered.

# Proposed Solution
**Provide a config option which will create the jaeger exporter with an [AgentEndpoint](https://pkg.go.dev/contrib.go.opencensus.io/exporter/jaeger#example-NewExporter-Agent).** Currently, only a `Endpoint` (CollectorEndpoint) is used. [#L22](https://github.com/krakendio/krakend-opencensus/blob/master/exporter/jaeger/jaeger.go#L22) is where this is initiated.

**Comment by alombarte** [comment]
Hi @CodyManshack-SAP ,

Thanks for the detailed issue. It is unclear to me if SAP is using Thrift over UDP and you have already the proposed solution tested and willing to do a PR, or if this is a feature that you are requesting from KrakenD to do?

thanks

**Comment by CodyManshack-SAP** [comment]
Hey @alombarte, 

Thanks for the quick response 😄

I have not tested the proposed solution, but since the library is simply just an interface to a well-tested library (the opencensus exporter), it seems that the proposed solution would be a rather straightforward implementation.

I could open a PR myself, but I'm not entirely sure about KrakenD's coding conventions. Additionally, it is unclear to me whether or not the improvement would be immediately available in v2.0.5 of KrakenD once merged.

**Comment by alombarte** [comment]
We are working today on the next release, and will be out today or monday probably, so I don't expect any new feature to be available in the next 3 months. There is time to work on this.

The conventions for coding we use are `go fmt`, nothing else.

I encourage you to submit a PR, and we will review it. The process for changing the behaviour of a new component is:

- Fork this repo
- Fork krakend-ce repo
- Edit the `go.mod` and notice the opencensus reference [here](https://github.com/krakendio/krakend-ce/blob/master/go.mod#L29)
- At the end of the file add a `replace` line pointing to your fork ([like these ones](https://github.com/krakendio/krakend-ce/blob/master/go.mod#L252-L256)). More information about replace [here](https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/)

You have the UDP environment set up and you will be able to confirm the feature.

Thank you

**Comment by CodyManshack-SAP** [comment]
Hi @alombarte,

I implemented, tested, and opened the PR above. Let me know if you need any further changes 😃

**Comment by alombarte** [comment]
Thanks @CodyManshack-SAP !

I am passing this to the team for review

**Comment by kpacha** [comment]
@CodyManshack-SAP We are releasing it in v2.2.0 (next minor release).

Thanks for your contribution!

**Comment by CodyManshack-SAP** [comment]
Happy to contribute
