### ISSUE TITLE
Migrate to OpenTelemetry

### ISSUE THREAD

**Issue by eminaktas** [krakend/krakend-opencensus#80]
Currently the packages  of opencensus used in the projects are public archives. They have merged their work under [OpenTelemetry](https://opentelemetry.io/). 

Their migration guide is posted [here](https://opentelemetry.io/blog/2023/sunsetting-opencensus/#how-to-migrate-to-opentelemetry).

> Warning
> 
> OpenCensus and OpenTracing have merged to form [OpenTelemetry](https://opentelemetry.io/), which serves as the next major version of OpenCensus and OpenTracing.
> 
> OpenTelemetry has now reached feature parity with OpenCensus, with tracing and metrics SDKs available in .NET, Golang, Java, NodeJS, and Python. All OpenCensus Github repositories, except [census-instrumentation/opencensus-python](https://github.com/census-instrumentation/opencensus-python), will be archived on July 31st, 2023. We encourage users to migrate to OpenTelemetry by this date.
> 
> To help you gradually migrate your instrumentation to OpenTelemetry, bridges are available in Java, Go, Python, and JS. [Read the full blog post to learn more](https://opentelemetry.io/blog/2023/sunsetting-opencensus/).

**Comment by dhontecillas** [comment]
@eminaktas thanks for the heads up. Work is already in progress to migrate to open telemetry, and will be published in https://github.com/krakend/krakend-otel  .

**Comment by eminaktas** [comment]
@dhontecillas thanks for your quick response. I had a feeling you were already working on this. I just wanted to make sure.
